import { describe, expect, it } from "vitest";
import { groupTabs } from "./tabGrouping";
import type { Tab, TabGroup } from "../bridge/types";

const makeTab = (id: string, title: string, url: string): Tab => ({
  id,
  title,
  url,
  isLoading: false,
  isActive: false,
});

const findGroup = (groups: TabGroup[], name: string) => groups.find((group) => group.name === name);

describe("groupTabs", () => {
  it("groups by strong domains first", () => {
    const tabs = [
      makeTab("1", "YouTube Video", "https://www.youtube.com/watch?v=1"),
      makeTab("2", "Design Doc", "https://docs.google.com/document/d/123"),
      makeTab("3", "Repo", "https://github.com/lumen/browser"),
    ];

    const result = groupTabs({ tabs, now: 0 });

    expect(result.groups.map((group) => group.name)).toEqual([
      "YouTube",
      "Google Docs",
      "GitHub",
    ]);
  });

  it("falls back to keyword grouping when no strong domain", () => {
    const tabs = [
      makeTab("1", "Login - Example", "https://example.com/login"),
      makeTab("2", "Invoice #123", "https://billing.example.com"),
    ];

    const result = groupTabs({ tabs, now: 0 });

    expect(findGroup(result.groups, "Accounts")?.tabIds).toEqual(["1"]);
    expect(findGroup(result.groups, "Shopping")?.tabIds).toEqual(["2"]);
  });

  it("groups by registrable domain for default case", () => {
    const tabs = [
      makeTab("1", "BBC News", "https://news.bbc.co.uk/world"),
      makeTab("2", "BBC Sport", "https://www.bbc.co.uk/sport"),
    ];

    const result = groupTabs({ tabs, now: 0 });

    const group = findGroup(result.groups, "bbc.co.uk");
    expect(group?.tabIds).toEqual(["1", "2"]);
  });

  it("merges single-tab groups into Misc when tab count > 12", () => {
    const tabs = Array.from({ length: 13 }, (_, index) =>
      makeTab(`tab-${index}`, `Site ${index}`, `https://site${index}.com`)
    );

    const result = groupTabs({ tabs, now: 0 });
    const misc = findGroup(result.groups, "Misc");

    expect(misc?.tabIds.length).toBe(13);
  });

  it("keeps user groups unless force is true", () => {
    const tabs = [
      makeTab("1", "Work Doc", "https://example.com/doc"),
      makeTab("2", "Design", "https://figma.com/file/123"),
    ];
    const existingGroups: TabGroup[] = [
      {
        id: "group-1",
        name: "Work",
        tabIds: ["1"],
        isAutoGenerated: false,
        createdAt: 1,
      },
    ];

    const result = groupTabs({ tabs, existingGroups, force: false, now: 0 });
    expect(result.groups.find((group) => group.id === "group-1")?.tabIds).toEqual(["1"]);

    const forced = groupTabs({ tabs, existingGroups, force: true, now: 0 });
    expect(forced.groups.find((group) => group.id === "group-1")).toBeUndefined();
  });
});
